### ISSUE TITLE
Link virker ikke

### ISSUE THREAD

**Issue by davidkonrad** [davidkonrad/edderkopper#2]
På "Baggrund" fanebladet: ”...som også omfatter oversigt over arternes forekomst i de 11 danske entomologiske faunistiske distrikter (**se kort her**).”
 
Linket virker ikke. Jeg har lavet et kort både som. jpg og. bmp. Kan det laves som en pop-up som man kan krydse væk igen, alternativt sættes på et nyt faneblad hvor der også er mulighed for at angive en billedtekst? Jeg har forsøgt at uploade billedfilen i jpg format nedenunder (kan ikke uploade i bmp format). Så bmp filen har du kun på mail, David.

**Comment by JorgenLissner** [comment]
![dkzooogiskeldistrikter](https://user-images.githubusercontent.com/47412900/52481713-8e689300-2baf-11e9-8176-516f1a980f25.jpg)
